; Adauga in ~/.config/polybar/config.ini
[module/wallpaper]
type = custom/text
content = WALL
content-padding = 1
content-foreground = ${colors.foreground}
click-left = ~/.config/quickshell/wallpaper-picker/toggle.sh

; apoi pune "wallpaper" in modules-left / modules-center / modules-right
